# Generated by Django 2.1.11 on 2019-10-11 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rememberMeApp', '0002_auto_20191011_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='rememberMeApp.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rememberMeApp.User'),
        ),
    ]
