# Generated by Django 2.1.11 on 2019-10-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rememberMeApp', '0003_auto_20191011_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='service',
        ),
    ]
