# Generated by Django 2.1.11 on 2019-10-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rememberMeApp', '0004_remove_password_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
